config/routes.rb
Rails.application.routes.draw do
  namespace :user_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    post 'profile', to: 'profile#update'
    patch 'profile', to: 'profile#update'
  end

  devise_for :users

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'suject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end

  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins #Administradores
    resources :subjects #Assuntos/Áreas
    resources :questions #Perguntas
  end
  
  devise_for :admins, skip: [:registrations]
  
  get 'inicio', to: 'site/welcome#index'

  get 'backoffice', to: 'admins_backoffice/welcome#index'
  root to: 'site/welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]  
  before_action :set_admin, only: [:edit,:update,:destroy]

  def index
    @admins = Admin.all.page(params[:page]).per(5)
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin,@admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso!"      
    else
      render :edit
    end    
  end
  
  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso!"      
    else
      render :index
    end    
  end

  private
  def params_admin
    params.require(:admin).permit(:email,:password,:password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password,:password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new,:edit]

  def index
    @questions = Question.all.includes(:subject)
                              .order(:description)
                              .page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"      
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluida com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description,:subject_id, answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end

end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit,:update,:destroy]

  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subject_path, notice: "Assunto/Área cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso!"      
    else
      render :edit
    end    
  end
  
  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"      
    else
      render :index
    end    
  end

  private
  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.total_users
    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Informe os parâmetros corretamente!"
    end
  end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial:'admins_backoffice/subjects/shared/form', locals: {action_message: 'Editando'} %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t('messages.listing',model:@subjects.model_name.human(count: 2)) %></h1>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= translate_attribute @subjects, :description %></th>
      <th>
        <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do%>
          <i class="fa fa-plus"></i>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.description %></td>
        <td style="width: 110px">
          <%= link_to  edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to  admins_backoffice_subject_path(subject), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: t('messages.confirm_with',item:subject.description.truncate(30))} do %>
            <i class="fa fa-minus"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div >
  <%= paginate @subjects %>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial:'admins_backoffice/subjects/shared/form', locals: {action_message: 'Novo'} %>